import { getBackreference, getLimetype } from '.';

export const infotiles = {
    name: 'infotiles',
    localname: {
        singular: 'InfoTile',
        plural: 'InfoTiles',
    },
    sort_order: 12,
    label: null,
    properties: {
        active: {
            name: 'active',
            required: false,
            label: 'none',
            fieldorder: 1,
            defaultvalue: true,
            localname: 'Active',
            type: 'yesno',
            has_sql: false,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        visiblefor: {
            name: 'visiblefor',
            required: false,
            label: 'none',
            fieldorder: 2,
            defaultvalue: {
                key: 'all',
                text: 'All',
                inactive: false,
            },
            localname: 'Visible for',
            type: 'option',
            has_sql: false,
            options: [
                {
                    key: 'all',
                    text: 'All',
                    inactive: false,
                },
                {
                    key: 'me',
                    text: 'Specific coworker',
                    inactive: false,
                },
                {
                    key: 'department',
                    text: 'Specific department',
                    inactive: true,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        operator: {
            name: 'operator',
            required: false,
            label: 'none',
            fieldorder: 4,
            defaultvalue: {
                key: 'count',
                text: 'Hitcount',
                inactive: false,
            },
            localname: 'Operator',
            type: 'option',
            has_sql: false,
            options: [
                {
                    key: 'field',
                    text: 'Field value',
                    inactive: true,
                },
                {
                    key: 'count',
                    text: 'Hitcount',
                    inactive: false,
                },
                {
                    key: 'link',
                    text: 'Link',
                    inactive: false,
                },
                {
                    key: 'sum',
                    text: 'Sum',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        visibleon: {
            name: 'visibleon',
            required: false,
            label: 'none',
            fieldorder: 5,
            defaultvalue: 'index',
            localname: 'Visble on',
            type: 'string',
            has_sql: false,
            length: 64,
            options: [
                {
                    key: '231401',
                    text: '',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        classname: {
            name: 'classname',
            required: true,
            label: 'none',
            fieldorder: 6,
            defaultvalue: '',
            localname: 'Tab',
            type: 'string',
            has_sql: false,
            length: 64,
            options: [
                {
                    key: '231501',
                    text: '',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        fieldname: {
            name: 'fieldname',
            required: false,
            label: 'none',
            fieldorder: 7,
            defaultvalue: '',
            localname: 'Field',
            type: 'string',
            has_sql: false,
            length: 64,
            options: [
                {
                    key: '231601',
                    text: '',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        filtername: {
            name: 'filtername',
            required: false,
            label: 'none',
            fieldorder: 8,
            defaultvalue: '',
            localname: 'Filter',
            type: 'string',
            has_sql: false,
            length: 256,
            options: [
                {
                    key: '231701',
                    text: '',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        icon: {
            name: 'icon',
            required: false,
            label: 'none',
            fieldorder: 9,
            defaultvalue: '',
            localname: 'Icon',
            type: 'string',
            has_sql: false,
            length: 256,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        label: {
            name: 'label',
            required: false,
            label: 'none',
            fieldorder: 10,
            defaultvalue: '',
            localname: 'Label in actionpad',
            type: 'string',
            has_sql: false,
            length: 256,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        sortorder: {
            name: 'sortorder',
            required: false,
            label: 'none',
            fieldorder: 11,
            defaultvalue: '',
            localname: 'Sort order',
            type: 'string',
            has_sql: false,
            length: 32,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        size: {
            name: 'size',
            required: false,
            label: 'none',
            fieldorder: 12,
            defaultvalue: {
                key: 'small',
                text: 'Small',
                inactive: false,
            },
            localname: 'Size',
            type: 'option',
            has_sql: false,
            options: [
                {
                    key: 'large',
                    text: 'Large',
                    inactive: false,
                },
                {
                    key: 'medium',
                    text: 'Medium',
                    inactive: false,
                },
                {
                    key: 'small',
                    text: 'Small',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        color: {
            name: 'color',
            required: true,
            label: 'none',
            fieldorder: 13,
            defaultvalue: {
                key: 'empty',
                text: '',
                inactive: false,
            },
            localname: 'Color',
            type: 'option',
            has_sql: false,
            options: [
                {
                    key: 'empty',
                    text: '',
                    inactive: false,
                },
                {
                    key: 'blue',
                    text: 'Blue',
                    inactive: false,
                },
                {
                    key: 'citrus',
                    text: 'Citrus',
                    inactive: false,
                },
                {
                    key: 'clean-green',
                    text: 'Clean-green',
                    inactive: false,
                },
                {
                    key: 'dark-grey',
                    text: 'Dark-grey',
                    inactive: false,
                },
                {
                    key: 'deep-red',
                    text: 'Deep-red',
                    inactive: false,
                },
                {
                    key: 'green',
                    text: 'Green',
                    inactive: false,
                },
                {
                    key: 'light-grey',
                    text: 'Light-grey',
                    inactive: false,
                },
                {
                    key: 'magenta',
                    text: 'Magenta',
                    inactive: false,
                },
                {
                    key: 'orange',
                    text: 'Orange',
                    inactive: false,
                },
                {
                    key: 'purple',
                    text: 'Purple',
                    inactive: false,
                },
                {
                    key: 'purple-rain',
                    text: 'Purple-rain',
                    inactive: false,
                },
                {
                    key: 'red',
                    text: 'Red',
                    inactive: false,
                },
                {
                    key: 'turquoise',
                    text: 'Turquoise',
                    inactive: false,
                },
                {
                    key: 'yellow',
                    text: 'Yellow',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        visibleonzero: {
            name: 'visibleonzero',
            required: false,
            label: 'none',
            fieldorder: 14,
            defaultvalue: false,
            localname: 'Visible on Zero',
            type: 'yesno',
            has_sql: false,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        coworker: {
            name: 'coworker',
            required: false,
            label: 'none',
            fieldorder: 3,
            defaultvalue: null,
            localname: 'Specific coworker',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () =>
                    getBackreference('coworker', 'infotiles'),
                getLimetype: () => getLimetype('coworker'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        id: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'id',
            localname: 'Record ID (System)',
            name: 'id',
            required: false,
            type: 'system',
            ui: {},
        },
        createduser: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'createduser',
            localname: 'Created by (System)',
            name: 'createduser',
            required: false,
            type: 'system',
            ui: {},
        },
        createdtime: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'createdtime',
            localname: 'Created (System)',
            name: 'createdtime',
            required: false,
            type: 'system',
            ui: {},
        },
        timestamp: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'timestamp',
            localname: 'Last updated (System)',
            name: 'timestamp',
            required: false,
            type: 'system',
            ui: {},
        },
        updateduser: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'updateduser',
            localname: 'Last updated by (System)',
            name: 'updateduser',
            required: false,
            type: 'system',
            ui: {},
        },
    },
    acl: {
        read: true,
        update: true,
        create: true,
        delete: true,
    },
    ui: {
        icon: 'decision',
        color: 'lime-light-grey',
        create: false,
        descriptive: ['_id'],
    },
};
