export const localize = {
    name: 'localize',
    localname: {
        singular: 'Localization',
        plural: 'Localizations',
    },
    sort_order: 17,
    label: null,
    properties: {
        owner: {
            name: 'owner',
            required: false,
            label: 'none',
            fieldorder: 1,
            defaultvalue: '',
            localname: 'Owner',
            type: 'string',
            has_sql: false,
            length: 64,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        code: {
            name: 'code',
            required: false,
            label: 'none',
            fieldorder: 2,
            defaultvalue: '',
            localname: 'Text code',
            type: 'string',
            has_sql: false,
            length: 32,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        sv: {
            name: 'sv',
            required: false,
            label: 'none',
            fieldorder: 7,
            defaultvalue: '',
            localname: 'Swedish',
            type: 'text',
            has_sql: false,
            length: 1073741823,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        en_us: {
            name: 'en_us',
            required: false,
            label: 'none',
            fieldorder: 8,
            defaultvalue: '',
            localname: 'English',
            type: 'text',
            has_sql: false,
            length: 1073741823,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        context: {
            name: 'context',
            required: false,
            label: 'none',
            fieldorder: 6,
            defaultvalue: '',
            localname: 'Context',
            type: 'string',
            has_sql: false,
            length: 512,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        fi: {
            name: 'fi',
            required: false,
            label: 'none',
            fieldorder: 11,
            defaultvalue: '',
            localname: 'Finnish',
            type: 'text',
            has_sql: false,
            length: 1073741823,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        no: {
            name: 'no',
            required: false,
            label: 'none',
            fieldorder: 9,
            defaultvalue: '',
            localname: 'Norwegian',
            type: 'text',
            has_sql: false,
            length: 1073741823,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        lookupcode: {
            name: 'lookupcode',
            required: false,
            label: 'none',
            fieldorder: 3,
            defaultvalue: '',
            localname: 'VBA Lookup code',
            type: 'string',
            has_sql: false,
            length: 128,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        formtag: {
            name: 'formtag',
            required: false,
            label: 'none',
            fieldorder: 4,
            defaultvalue: '',
            localname: 'VBA Form tag',
            type: 'string',
            has_sql: false,
            length: 256,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        da: {
            name: 'da',
            required: false,
            label: 'none',
            fieldorder: 10,
            defaultvalue: '',
            localname: 'Danish',
            type: 'text',
            has_sql: false,
            length: 1073741823,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        aplocalizecode: {
            name: 'aplocalizecode',
            required: false,
            label: 'none',
            fieldorder: 5,
            defaultvalue: '',
            localname: 'Actionpad translation code',
            type: 'string',
            has_sql: false,
            length: 128,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        id: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'id',
            localname: 'Record ID (System)',
            name: 'id',
            required: false,
            type: 'system',
            ui: {},
        },
        createduser: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'createduser',
            localname: 'Created by (System)',
            name: 'createduser',
            required: false,
            type: 'system',
            ui: {},
        },
        createdtime: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'createdtime',
            localname: 'Created (System)',
            name: 'createdtime',
            required: false,
            type: 'system',
            ui: {},
        },
        timestamp: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'timestamp',
            localname: 'Last updated (System)',
            name: 'timestamp',
            required: false,
            type: 'system',
            ui: {},
        },
        updateduser: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'updateduser',
            localname: 'Last updated by (System)',
            name: 'updateduser',
            required: false,
            type: 'system',
            ui: {},
        },
    },
    acl: {
        read: true,
        update: true,
        create: true,
        delete: true,
    },
    ui: {
        icon: 'decision',
        color: 'lime-light-grey',
        create: false,
        descriptive: ['_id'],
    },
};
