import { getBackreference, getLimetype } from '.';

export const solutionimprovement = {
    name: 'solutionimprovement',
    localname: {
        singular: 'Solution improvement',
        plural: 'Solution improvements',
    },
    sort_order: 13,
    label: null,
    properties: {
        card: {
            name: 'card',
            required: false,
            label: 'none',
            fieldorder: 3,
            defaultvalue: '-',
            localname: 'Card',
            type: 'string',
            has_sql: false,
            length: 32,
            options: [
                {
                    key: 'other',
                    text: 'Other',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        priority: {
            name: 'priority',
            required: false,
            label: 'none',
            fieldorder: 4,
            defaultvalue: {
                key: 'wish',
                text: 'Wish',
                inactive: false,
            },
            localname: 'Priority',
            type: 'option',
            has_sql: false,
            options: [
                {
                    key: 'better',
                    text: 'Better late then never',
                    inactive: false,
                },
                {
                    key: 'urgent',
                    text: 'Urgent',
                    inactive: false,
                },
                {
                    key: 'wish',
                    text: 'Wish',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        title: {
            name: 'title',
            required: true,
            label: 'none',
            fieldorder: 5,
            defaultvalue: '',
            localname: 'Title',
            type: 'string',
            has_sql: false,
            length: 128,
            options: [],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        misc: {
            name: 'misc',
            required: false,
            label: 'none',
            fieldorder: 6,
            defaultvalue: '',
            localname: 'Detailed description',
            type: 'text',
            has_sql: false,
            length: 512,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        solutionimprovementstatus: {
            name: 'solutionimprovementstatus',
            required: false,
            label: 'none',
            fieldorder: 7,
            defaultvalue: {
                key: 'reported',
                text: 'Reported',
                inactive: false,
            },
            localname: 'Status',
            type: 'option',
            has_sql: false,
            options: [
                {
                    key: 'reported',
                    text: 'Reported',
                    inactive: false,
                },
                {
                    key: 'approved',
                    text: 'Approved',
                    inactive: false,
                },
                {
                    key: 'started',
                    text: 'Ongoing',
                    inactive: false,
                },
                {
                    key: 'More info needed',
                    text: 'More information needed',
                    inactive: false,
                },
                {
                    key: 'done',
                    text: 'Done',
                    inactive: false,
                },
                {
                    key: 'deny',
                    text: 'Declined',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        donedate: {
            name: 'donedate',
            required: false,
            label: 'none',
            fieldorder: 10,
            defaultvalue: null,
            localname: 'Rejection/Done date',
            type: 'date',
            has_sql: false,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        comment: {
            name: 'comment',
            required: false,
            label: 'none',
            fieldorder: 11,
            defaultvalue: '',
            localname: 'Comment/Solution/Decision',
            type: 'text',
            has_sql: false,
            length: 512,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        coworker: {
            name: 'coworker',
            required: false,
            label: 'none',
            fieldorder: 8,
            defaultvalue: null,
            localname: 'Responsible',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () =>
                    getBackreference('coworker', 'solutionimprovement'),
                getLimetype: () => getLimetype('coworker'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        created: {
            name: 'created',
            required: false,
            label: 'none',
            fieldorder: 1,
            defaultvalue: '2020-04-07T12:13:49.932793+02:00',
            localname: 'Created',
            type: 'time',
            has_sql: false,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        latestupdate: {
            name: 'latestupdate',
            required: false,
            label: 'none',
            fieldorder: 9,
            defaultvalue: null,
            localname: 'Last update',
            type: 'time',
            has_sql: false,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        coworkercreatedby: {
            name: 'coworkercreatedby',
            required: false,
            label: 'none',
            fieldorder: 2,
            defaultvalue: null,
            localname: 'Created by',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () =>
                    getBackreference(
                        'coworkercreatedby',
                        'solutionimprovement'
                    ),
                getLimetype: () => getLimetype('coworkercreatedby'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        id: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'id',
            localname: 'Record ID (System)',
            name: 'id',
            required: false,
            type: 'system',
            ui: {},
        },
        createduser: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'createduser',
            localname: 'Created by (System)',
            name: 'createduser',
            required: false,
            type: 'system',
            ui: {},
        },
        createdtime: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'createdtime',
            localname: 'Created (System)',
            name: 'createdtime',
            required: false,
            type: 'system',
            ui: {},
        },
        timestamp: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'timestamp',
            localname: 'Last updated (System)',
            name: 'timestamp',
            required: false,
            type: 'system',
            ui: {},
        },
        updateduser: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'updateduser',
            localname: 'Last updated by (System)',
            name: 'updateduser',
            required: false,
            type: 'system',
            ui: {},
        },
    },
    acl: {
        read: true,
        update: true,
        create: true,
        delete: true,
    },
    ui: {
        icon: 'decision',
        color: 'lime-light-grey',
        create: false,
        descriptive: ['_id'],
    },
};
