import { getBackreference, getLimetype } from '.';

export const todo = {
    name: 'todo',
    localname: {
        singular: 'To-do',
        plural: "To-do's",
    },
    sort_order: 6,
    label: 'todo',
    properties: {
        subject: {
            name: 'subject',
            required: false,
            label: 'description',
            fieldorder: 1,
            defaultvalue: '',
            localname: 'Subject',
            type: 'string',
            has_sql: false,
            length: 128,
            options: [
                {
                    key: 'followupquote',
                    text: 'Follow up quote',
                    inactive: false,
                },
                {
                    key: 'customervisit',
                    text: 'Customer visit',
                    inactive: false,
                },
                {
                    key: 'call',
                    text: 'Call',
                    inactive: false,
                },
                {
                    key: 'salescall',
                    text: 'Sales call',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        starttime: {
            name: 'starttime',
            required: true,
            label: 'startdate',
            fieldorder: 4,
            defaultvalue: '2020-04-07T12:13:49.985289+02:00',
            localname: 'Start time',
            type: 'time',
            has_sql: false,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        endtime: {
            name: 'endtime',
            required: false,
            label: 'duedate',
            fieldorder: 5,
            defaultvalue: null,
            localname: 'End time',
            type: 'time',
            has_sql: false,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        done: {
            name: 'done',
            required: false,
            label: 'completed',
            fieldorder: 6,
            defaultvalue: false,
            localname: 'Done',
            type: 'yesno',
            has_sql: false,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        note: {
            name: 'note',
            required: false,
            label: 'notes',
            fieldorder: 8,
            defaultvalue: '',
            localname: 'Notes',
            type: 'text',
            has_sql: false,
            length: 1024,
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        coworker: {
            name: 'coworker',
            required: false,
            label: 'responsiblecoworker',
            fieldorder: 3,
            defaultvalue: null,
            localname: 'Coworker',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () => getBackreference('coworker', 'todo'),
                getLimetype: () => getLimetype('coworker'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        company: {
            name: 'company',
            required: false,
            label: 'none',
            fieldorder: 9,
            defaultvalue: null,
            localname: 'Company',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () => getBackreference('company', 'todo'),
                getLimetype: () => getLimetype('company'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        campaign: {
            name: 'campaign',
            required: false,
            label: 'none',
            fieldorder: 12,
            defaultvalue: null,
            localname: 'Marketing activity',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () => getBackreference('campaign', 'todo'),
                getLimetype: () => getLimetype('campaign'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        helpdesk: {
            name: 'helpdesk',
            required: false,
            label: 'none',
            fieldorder: 11,
            defaultvalue: null,
            localname: 'Helpdesk',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () => getBackreference('helpdesk', 'todo'),
                getLimetype: () => getLimetype('helpdesk'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        person: {
            name: 'person',
            required: false,
            label: 'name',
            fieldorder: 2,
            defaultvalue: null,
            localname: 'Person',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () => getBackreference('person', 'todo'),
                getLimetype: () => getLimetype('person'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        deal: {
            name: 'deal',
            required: false,
            label: 'none',
            fieldorder: 10,
            defaultvalue: null,
            localname: 'Deal',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () => getBackreference('deal', 'todo'),
                getLimetype: () => getLimetype('deal'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        history: {
            name: 'history',
            required: false,
            label: 'none',
            fieldorder: 14,
            defaultvalue: '',
            localname: 'Company history',
            type: 'hasandbelongstomany',
            has_sql: true,
            relation: {
                getBackreference: () => getBackreference('history', 'todo'),
                getLimetype: () => getLimetype('history'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        todostatus: {
            name: 'todostatus',
            required: false,
            label: 'none',
            fieldorder: 7,
            defaultvalue: {
                key: 'empty',
                text: '',
                inactive: false,
            },
            localname: 'To-do status',
            type: 'option',
            has_sql: true,
            options: [
                {
                    key: 'empty',
                    text: '',
                    inactive: false,
                },
                {
                    key: 'delayed',
                    text: 'Delayed',
                    inactive: false,
                },
                {
                    key: 'done',
                    text: 'Done',
                    inactive: false,
                },
                {
                    key: 'future',
                    text: 'Future',
                    inactive: false,
                },
                {
                    key: 'active',
                    text: 'Just do it!',
                    inactive: false,
                },
            ],
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        deal2: {
            name: 'deal2',
            required: false,
            label: 'none',
            fieldorder: 15,
            defaultvalue: '',
            localname: 'Deals (HIDDEN)',
            type: 'hasmany',
            has_sql: true,
            relation: {
                getBackreference: () => getBackreference('deal', 'todo2'),
                getLimetype: () => getLimetype('deal'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        successplan: {
            name: 'successplan',
            required: false,
            label: 'none',
            fieldorder: 13,
            defaultvalue: null,
            localname: 'Success plan',
            type: 'belongsto',
            has_sql: false,
            relation: {
                getBackreference: () => getBackreference('successplan', 'todo'),
                getLimetype: () => getLimetype('successplan'),
            },
            acl: {
                read: true,
                update: true,
                create: true,
                delete: true,
            },
            ui: {},
        },
        id: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'id',
            localname: 'Record ID (System)',
            name: 'id',
            required: false,
            type: 'system',
            ui: {},
        },
        createduser: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'createduser',
            localname: 'Created by (System)',
            name: 'createduser',
            required: false,
            type: 'system',
            ui: {},
        },
        createdtime: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'createdtime',
            localname: 'Created (System)',
            name: 'createdtime',
            required: false,
            type: 'system',
            ui: {},
        },
        timestamp: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'timestamp',
            localname: 'Last updated (System)',
            name: 'timestamp',
            required: false,
            type: 'system',
            ui: {},
        },
        updateduser: {
            acl: {},
            defaultvalue: null,
            fieldorder: 1,
            label: 'updateduser',
            localname: 'Last updated by (System)',
            name: 'updateduser',
            required: false,
            type: 'system',
            ui: {},
        },
    },
    acl: {
        read: true,
        update: true,
        create: true,
        delete: true,
    },
    ui: {
        icon: 'todo_list',
        color: 'lime-turquoise',
        create: false,
        descriptive: ['subject'],
    },
};
